//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 11/28/2014 15:28:09
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Prism.StoreApps.Extensions.ViewModel.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class DialogCommandStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static DialogCommandStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(DialogCommandStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("DialogCommandStrings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/DialogCommandStrings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Abort"
        /// </summary>
        public static string Abort
        {
            get
            {
                return resourceLoader.GetString("Abort");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cancel"
        /// </summary>
        public static string Cancel
        {
            get
            {
                return resourceLoader.GetString("Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Ignore"
        /// </summary>
        public static string Ignore
        {
            get
            {
                return resourceLoader.GetString("Ignore");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No"
        /// </summary>
        public static string No
        {
            get
            {
                return resourceLoader.GetString("No");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Ok"
        /// </summary>
        public static string Ok
        {
            get
            {
                return resourceLoader.GetString("Ok");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Retry"
        /// </summary>
        public static string Retry
        {
            get
            {
                return resourceLoader.GetString("Retry");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "qwe"
        /// </summary>
        public static string Test
        {
            get
            {
                return resourceLoader.GetString("Test");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Yes"
        /// </summary>
        public static string Yes
        {
            get
            {
                return resourceLoader.GetString("Yes");
            }
        }
    }
}
