//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 11/28/2014 15:31:42
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Prism.StoreApps.Extensions.UI.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class ErrorStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static ErrorStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ErrorStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("ErrorStrings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/ErrorStrings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unable to show two dialog at the same time"
        /// </summary>
        public static string AlertMessage_ShowTwoDialog
        {
            get
            {
                return resourceLoader.GetString("AlertMessage_ShowTwoDialog");
            }
        }
    }
}
